language: node_js

services:
  - docker

before_install:
  - sudo apt-get update
  - docker ps

script: docker-compose build

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: sprint4/ci-cd
