version: "3"
services:
  preferences-db:
    image: postgres
    environment:
      POSTGRES_DB: preferences
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata-preferences:/var/lib/postgresql/data
    ports:
      - "5434:5432"
  preferences-service:
    build: ./preferences-service
    command: npm run start:dev
    ports:
      - "8082:8081"
    volumes:
      - ./preferences-service:/app
    depends_on:
      - preferences-db
  core-db:
    image: postgres
    environment:
      POSTGRES_DB: core
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata-core:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  core-api:
    build: ./core-api
    command: npm run start:dev
    ports:
      - "8080:8080"
    volumes:
      - ./core-api:/app
    depends_on:
      - core-db
      - preferences-service