version: "3"
services:
  preference-db:
    image: postgres
    container_name: preference-db
    environment:
      POSTGRES_DB: preference
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata-preference:/var/lib/postgresql/data
    ports:
      - "5434:5432"
  preference-service:
    build: ./preference-service
    command: npm run start:dev
    container_name: preference
    ports:
      - "8082:8081"
    volumes:
      - ./preference-service:/app
      - /app/node_modules
    depends_on:
      - preference-db
  order-db:
    image: postgres
    container_name: order-db
    environment:
      POSTGRES_DB: order
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata-order:/var/lib/postgresql/data
    ports:
      - "5435:5432"
  order-service:
    build: ./order-service
    command: npm run start:dev
    container_name: order
    ports:
      - "8083:8081"
    volumes:
      - ./order-service:/app
      - /app/node_modules
    depends_on:
      - order-db
  notification-db:
    image: postgres
    container_name: notification-db
    environment:
      POSTGRES_DB: notification
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata-notification:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  notification-service:
    build: ./notification-service
    command: npm run start:dev
    container_name: notification
    ports:
      - "8081:8081"
    volumes:
      - ./notification-service:/app
      - /app/node_modules
    depends_on:
      - notification-db
  core-db:
    image: postgres
    container_name: core-db
    environment:
      POSTGRES_DB: core
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata-core:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  core-api:
    build: ./core-api
    command: npm run start:dev
    container_name: core
    ports:
      - "8080:8080"
    volumes:
      - ./core-api:/app
      - /app/node_modules
    depends_on:
      - core-db
      - order-service
      - preference-service
      - notification-service
